patchesStrategicMerge:
- deployment-patch.yaml
- service-patch.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ongiv/argoCD_test
  newTag: "81"
- name: ongiv/hello_jenkins
  newTag: "141"
